[package]
name = "nh"
version = "3.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = [
    "derive",
    "env",
] }
clap_complete = { version = "4.0" }
fern = { version = "0.6" }
log = { version = "0.4" }
anyhow = { version = "1.0" }

[build-dependencies]
clap = { version = "4.0", features = [
    "derive",
    "env",
] }
clap_complete = { version = "4.0" }
