[package]
name = "nh"
version = "3.1.3"
edition = "2021"
license = "EUPL-1.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = [
    "derive",
    "env",
] }
clap_complete = "4.0"
fern = { version = "0.6", features = [
    "colored",
] }
log = "0.4"
anyhow = "1.0"
hostname = "^0.3"
clean-path = "0.2"
subprocess = "0.2"
dialoguer = { version = "0.10.2", default-features = false }
thiserror = "1.0"
derive_builder = "0.12.0"
tempfile = "3.5.0"
nix = { version = "0.26.2", default-features = false, features = ["user", "fs"] }

[build-dependencies]
clap = { version = "4.0", features = [
    "derive",
    "env",
] }
clap_complete = "4.0"
