name: "Build NH"

on:
  pull_request:
  push:
    branches-ignore:
      - 'update-*'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Install Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Checkout
        uses: actions/checkout@v3

      - run: nix build -L
