name: "Build NH"

on:
  pull_request:
  push:
    branches-ignore:
      - 'update-*'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Install Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix build github:$GITHUB_REPOSITORY/$GITHUB_SHA -L

      - name: NixOS check
        env:
          out: /nixos
        run: |
          export
          sudo mkdir -pv $out
          sudo mount -t tmpfs none $out
          nix build nixpkgs#nixos-install-tools
          sudo ./result/bin/nixos-install \
            --flake github:$GITHUB_REPOSITORY/$GITHUB_SHA#check \
            --root $out \
            --no-root-passwd \
            --no-bootloader
