name: "Build NH"

on:
  pull_request:
  push:
    branches-ignore:
      - 'update-*'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Set up cachix
        uses: cachix/cachix-action@master
        with:
          name: viperml
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Checkout
        uses: actions/checkout@v3

      - run: nix build -L
